fix: Make lease time configurable
open-telemetry/opentelemetry-operator pull request #1134
Opened 2022-10-01 18:56 UTC by albertollamaso

With this change `lease time` can be customized via the environment variable `LEASE_TIME`.

If environment variable is not set, manager will use default lease time defined in code.

See https://github.com/open-telemetry/opentelemetry-operator/issues/1073

2022-10-03 08:27 UTC, pavolloffay commented on main.go
> +	leaseTime, found := os.LookupEnv("LEASE_TIME")
To be consistent with the configuration mechanism that the operator already uses I would propose to change this to a flag.

2023-11-28 22:02 UTC, jaronoff97 requested changes

2023-11-28 22:02 UTC, jaronoff97 commented on main.go
> +		leaseTime                 int
This should probably just be a duration instead of an integer

2023-11-28 22:02 UTC, jaronoff97 commented
@albertollamaso are you interested in working this still? Left a comment if so!

2023-11-28 22:03 UTC, jaronoff97 commented
closes #1073

2023-11-29 15:59 UTC, albertollamaso commented
> @albertollamaso are you interested in working this still? Left a comment if so!

I'll have time to check in few weeks 🙏

2025-03-12 20:24 UTC, atoulme commented
Closing as inactive. Please comment if you would like to reopen this pull request.

2025-03-12 20:24 UTC, closed without merging