*: Fix `make` on MacOS by using `gsed` + use non-default cluster name for `kind`
open-telemetry/opentelemetry-operator pull request #1500
Opened 2023-02-22 17:08 UTC by matej-g

This PR puts together two small suggested improvements to the `Makefile`:
- Opt for using `gsed` instead of the MacOS version of `sed`, which is incompatible with certain flags that work on Linux
- Use non-default name for the `kind` cluster and make it configurable. Often, when testing locally, the default cluster (`kind`) will already exist, making the the operation fail.

I believe changelog can be skipped.

2023-02-23 10:39 UTC, iblancasa requested changes
Could you send a PR for each change? Since they are not related, I think it would make more sense.

Also, add `[chore]` to the title of your PRs to skip the changelog.

2023-02-23 16:42 UTC, matej-g commented
@iblancasa done

2023-02-27 09:59 UTC, iblancasa requested changes
Could you rerun the CI?
```sh
git commit -sm "Add commit to trigger build" --allow-empty
```

2023-02-28 15:32 UTC, matej-g commented
I assume the failure is a flaky test and not related @open-telemetry/operator-approvers?

2023-02-28 16:01 UTC, iblancasa approved these changes

2023-02-28 17:37 UTC, jaronoff97 approved these changes

2023-02-28 17:37 UTC, merged