feat(nodejs): bump nodejs in version.txt
open-telemetry/opentelemetry-operator pull request #1683
Opened 2023-04-27 15:07 UTC by mat-rumian

PR update nodejs autoinstrumentation in version.txt. 

Note: previous version `0.37.0` wasn't correct (it should be 0.36.0 as 0.37.0 was never released)

2023-04-27 15:34 UTC, mat-rumian commented
I'm sorry needed to change version to `0.38.0` as it corresponds to `@opentelemetry/sdk-node`. I'm not sure if it's right. I was expecting this to match package `@opentelemetry/auto-instrumentations-node` which defines versions of the installed instrumentation packages.

2023-04-27 15:49 UTC, jaronoff97 commented on versions.txt
> +autoinstrumentation-nodejs=0.38.0
Do we need to upgrade [this](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/package.json#L18) as well?

2023-04-27 16:15 UTC, VineethReddy02 requested changes
@mat-rumian, I don't think the version should be updated in `versions.txt`. Normally, `versions.txt` is bumped during the release process to publish the latest auto-inst for supported languages. Instead, it should be updated in the `auto-instrumentation` directory.

Here's an example of how the last Node.js bump to the latest version was performed: [https://github.com/open-telemetry/opentelemetry-operator/pull/1626/files](https://github.com/open-telemetry/opentelemetry-operator/pull/1626/files)

Also, [here](https://github.com/open-telemetry/opentelemetry-operator/pull/1640/files) is an example of how python versions are bumped.

2023-04-29 18:51 UTC, ankit-gautam23 approved these changes
LGTM

2023-09-07 15:29 UTC, TylerHelmuth commented
This PR is no longer needed since we've upgraded past 0.38.0

2023-09-07 15:29 UTC, closed without merging