Promote @TylerHelmuth to Approver
open-telemetry/opentelemetry-operator pull request #1723
Opened 2023-05-08 18:48 UTC by TylerHelmuth

Hello!

I would like top formally request to be made an Approver for opentelemetry-operator. I have been an active contributor to this repo since December 2022 helping out in issues, PR reviews, and [contributing PRs](https://github.com/open-telemetry/opentelemetry-operator/pulls/TylerHelmuth), with a focus on our Instrumentation capabilities. I also re-organized and filled in [opentelemetry.io's Operator auto-instrumentation docs](https://opentelemetry.io/docs/k8s-operator/automatic/).

I would like to continue driving progress in this space by helping out in a formal capacity.

/cc @open-telemetry/operator-maintainers

2023-05-08 21:14 UTC, jaronoff97 commented
I support this!!!

2023-05-08 21:15 UTC, jaronoff97 approved these changes

2023-05-09 07:49 UTC, pavolloffay commented
I support this

2023-05-09 07:49 UTC, pavolloffay approved these changes

2023-05-10 08:03 UTC, frzifus approved these changes

2023-05-10 08:15 UTC, pavolloffay commented
from: https://github.com/open-telemetry/community/blob/main/community-membership.md#approver it seems almost all requirements are met (except @VineethReddy02 opinion). Also the nomination should have come from another maintainer. 


@VineethReddy02 do you have any objections for @TylerHelmuth nomination?

2023-05-10 08:16 UTC, pavolloffay requested changes
Could you please add yourself to the release managers https://github.com/open-telemetry/opentelemetry-operator/blob/4886a78142d92531b1c054d95f45e4a61fd726b4/RELEASE.md#L35 ? 

It's one of the responsibilities of the approver in the operator.

2023-05-10 08:16 UTC, pavolloffay requested changes
Could you please add yourself to the release managers https://github.com/open-telemetry/opentelemetry-operator/blob/4886a78142d92531b1c054d95f45e4a61fd726b4/RELEASE.md#L35 ? 

It's one of the responsibilities of the approver in the operator.

2023-05-10 14:59 UTC, TylerHelmuth commented
@pavolloffay added myself in the release schedule (ahead of @frzifus since they just did 0.76.1)

2023-05-10 16:06 UTC, pavolloffay approved these changes

2023-05-10 19:53 UTC, jvoravong approved these changes

2023-05-10 19:57 UTC, tigrannajaryan commented
I added @TylerHelmuth to @open-telemetry/operator-approvers

2023-05-10 20:29 UTC, merged

2023-05-10 20:35 UTC, TylerHelmuth commented
Thanks everyone! Looking forward to helping out more.