Use distroless base for target allocator and opamp bridge images
open-telemetry/opentelemetry-operator pull request #2010
Opened 2023-08-10 16:36 UTC by swiatekm-sumo

2023-08-11 15:19 UTC, bryan-aguilar commented
Oops, commented on the issue rather than this PR. copy/pasting what I put into the issue here. 

> I'd vote for scratch just for the sake of reducing the security surface area even further. Is there a reason to prefer distroless over scratch other than consistency?

2023-08-11 16:03 UTC, jaronoff97 approved these changes

2023-08-11 16:36 UTC, iblancasa approved these changes

2023-08-11 16:41 UTC, bryan-aguilar requested changes
I would prefer to see scratch image used instead of distroless. Scratch reduces the security surface area. Unless there is a strong reason to use distroless I believe that is a better path forward.

2023-08-16 15:56 UTC, swiatekm-sumo commented
Closing in favor of #2014

2023-08-16 15:56 UTC, closed without merging