Release 0.84.0
open-telemetry/opentelemetry-operator pull request #2092
Opened 2023-09-07 09:50 UTC by yuriolisa

Resolves #2071

2023-09-07 10:39 UTC, swiatekm-sumo approved these changes

2023-09-07 11:31 UTC, iblancasa approved these changes

2023-09-07 14:36 UTC, TylerHelmuth commented
Would be great to get these 2 PRs merged first: 
- https://github.com/open-telemetry/opentelemetry-operator/pull/2087
- https://github.com/open-telemetry/opentelemetry-operator/pull/2096

2023-09-07 15:29 UTC, TylerHelmuth commented
https://github.com/open-telemetry/opentelemetry-operator/pull/1683 was out-of-date, I have closed it.

2023-09-08 05:04 UTC, Kielek commented on versions.txt
Please update also .NET version here as #2096 was merged

2023-09-12 11:34 UTC, frzifus requested changes
LGTM, only one tiny thing ^^

2023-09-12 11:34 UTC, frzifus commented on CHANGELOG.md
> +- `operator`: Make OpenShift Route work with gRPC receivers by using h2c appProtocol (#1969)
```suggestion
- `operator`: Make OpenShift Route work with gRPC receivers by using h2c appProtocol (#1969)

### Components
TBD
```

Should we add the component section here too?

2023-09-13 09:42 UTC, pavolloffay commented on CHANGELOG.md
> -<!-- next version -->
This should not be removed and instead moved  above the #0.84.0

2023-09-13 09:47 UTC, frzifus approved these changes

2023-09-13 09:51 UTC, pavolloffay commented
The PR needs to be rebased to include https://github.com/open-telemetry/opentelemetry-operator/blob/main/.chloggen/remove_ta_defaults.yaml

2023-09-13 09:53 UTC, pavolloffay approved these changes

2023-09-13 12:36 UTC, merged