[chore] Refactor Webhooks to their own packages
open-telemetry/opentelemetry-operator pull request #2210
Opened 2023-10-11 16:48 UTC by jaronoff97

**Description:** 
This PR updates how webhooks are created and managed by the operator by moving them out of types and into an internal package. In the future this will let us add more complex logic to the webhooks, but for now this mostly is a no-op. One benefit for instrumentation webhooks is that we no longer need to add the annotations to the resource for defaulting because we can add a config field to the instrumentation webhook. All tests have been moved over and replaced with the actual webhooks.

**Link to tracking Issue:** n/a

**Testing:** tested locally.

**Documentation:** n/a

2023-10-11 16:48 UTC, jaronoff97 commented on config/webhook/manifests.yaml
The order of these is reversing, but is a noop AFAICT

2023-10-11 19:36 UTC, jaronoff97 commented on pkg/instrumentation/upgrade/upgrade.go
> +func (u *InstrumentationUpgrade) upgrade(_ context.Context, inst v1alpha1.Instrumentation) *v1alpha1.Instrumentation {
the previous way was really annoying me. If anyone has problems with this, i am happy to revert it.

2023-10-11 20:05 UTC, TylerHelmuth commented on internal/webhook/instrumentation/webhook.go
> +	r.Annotations[constants.AnnotationDefaultAutoInstrumentationNginx] = w.cfg.AutoInstrumentationNginxImage()
Where were we setting these values before?

2023-10-11 20:15 UTC, jaronoff97 commented on cmd/operator-opamp-bridge/agent/agent_test.go
> +					LastRemoteConfigHash: []byte("good/testnamespace401"),
this was a bug that got pushed when i merged my config PR somehow, not sure how it got through.

2023-10-11 20:17 UTC, jaronoff97 commented on cmd/operator-opamp-bridge/agent/agent_test.go
> +					LastRemoteConfigHash: []byte("good/testnamespace401"),
i could push a separate PR with this if you want, i just wanted my tests to pass haha

2023-10-11 20:20 UTC, TylerHelmuth approved these changes
LGTM

2023-10-12 10:11 UTC, swiatekm-sumo approved these changes
LGTM

2023-10-12 16:03 UTC, pavolloffay commented on config/webhook/manifests.yaml
> +      path: /mutate-opentelemetry-io-v1alpha1-opentelemetrycollector
why are these changes here? 

I am concerned that this will cause issues for the upgrade (also the upgrade test was changed )

2023-10-13 18:32 UTC, jaronoff97 commented
@pavolloffay should be good to go now!

2023-10-16 08:26 UTC, pavolloffay requested changes

2023-10-16 08:26 UTC, pavolloffay commented on internal/webhook/sidecar/webhookhandler.go
> +package sidecar
I don't think we should call this package `sidecar` 

The package exposes a mutator API that allows mutating pod objects. It is used for instrumentation and sidecar

2023-10-17 06:46 UTC, pavolloffay approved these changes

2023-10-17 06:46 UTC, merged