Fix service account is created even when one is specified in collector spec
open-telemetry/opentelemetry-operator pull request #2378
Opened 2023-11-21 03:22 UTC by changexd

**Description:** <Describe what has changed.>
Fix service account is created even when one is specified in collector spec 

**Link to tracking Issue:** <Issue number if applicable>
#2372

2023-11-21 09:58 UTC, swiatekm-sumo reviewed
Could you add a test verifying that the ServiceAccount *doeesn't* get created if the value is set? LGTM otherwise.

2023-11-21 15:25 UTC, jaronoff97 requested changes

2023-11-21 15:25 UTC, jaronoff97 commented on internal/manifests/collector/collector.go
> -		manifests.FactoryWithoutError(ServiceAccount),
Could we instead just check this in the service account manifest? In the builder we would then return nil if service account is set

2023-11-22 03:06 UTC, changexd commented
I wasn't sure if the test should be placed in service account manifest, so I simply added test to builder since we would like to check if the builder build service account manifest when specified.

2023-11-24 14:56 UTC, jaronoff97 approved these changes

2023-11-24 16:13 UTC, pavolloffay approved these changes

2023-11-24 16:14 UTC, merged