Add missing label servicemonitor
open-telemetry/opentelemetry-operator pull request #2573
Opened 2024-01-29 11:08 UTC by yuriolisa

**Description:** <Describe what has changed.>

Add missing label for Service/Pod Monitors
**Link to tracking Issue:** <Issue number if applicable>
Resolves #2251 
**Testing:** <Describe what testing was performed and which tests were added.>
Added unit and e2e tests. 
**Documentation:** <Describe the documentation added.>

2024-01-29 11:37 UTC, swiatekm-sumo commented
Could we use `manifestutils.Labels` for these?

2024-01-29 12:05 UTC, yuriolisa commented
> Could we use `manifestutils.Labels` for these?

No, but I could include a PodMonitorSelector and ServiceMonitorSelector. WDYT?

2024-01-29 17:26 UTC, jaronoff97 commented on internal/manifests/collector/podmonitor.go
> +					"app.kubernetes.io/name":       "otel-collector-monitoring",
I don't think this name is accurate, as mikolaj said we need to use manifestutils here to select the right instance. ([ex](https://github.com/open-telemetry/opentelemetry-operator/blob/ca0b9498f48fdf6bba3687d3a193bed685eba2e9/internal/manifests/manifestutils/labels.go#L67-L69)) Further, I don't believe the name for the podmonitor will contain the -monitoring suffix as we only add that for the monitoring service.

2024-01-29 17:34 UTC, jaronoff97 requested changes
@yuriolisa i left a [comment](https://github.com/open-telemetry/opentelemetry-operator/issues/2251#issuecomment-1915234212) on the original issue for how I think we should solve this. Let me know your thoughts.

2024-01-30 20:12 UTC, jaronoff97 reviewed
A few questions. Do we have an e2e test for this that checks that we successfully pulled metrics based on the SM/PM?

2024-01-30 20:12 UTC, jaronoff97 commented on internal/manifests/manifestutils/labels.go
> +func SelectorMatchLabels(instance metav1.ObjectMeta, component string) map[string]string {
can you add a comment on hows this is different from the selector labels?

2024-01-30 20:12 UTC, jaronoff97 commented on tests/e2e-prometheuscr/create-pm-prometheus-exporters/01-assert.yaml
> +      app.kubernetes.io/name: otel-collector-monitoring
i don't think this will match the pod because it won't have this name?

2024-01-30 20:12 UTC, jaronoff97 commented on tests/e2e-prometheuscr/create-sm-prometheus-exporters/01-assert.yaml
> +      app.kubernetes.io/name: otel-collector-monitoring
shouldn't this be something like simplest-collector-monitoring?

2024-01-30 20:12 UTC, jaronoff97 commented on internal/manifests/manifestutils/labels.go
> +		"app.kubernetes.io/name":       "otel-collector-monitoring",
don't we want this to match the monitoring service's name?

2024-01-31 19:33 UTC, jaronoff97 approved these changes

2024-01-31 19:33 UTC, jaronoff97 commented on internal/manifests/collector/podmonitor_test.go
> +		"app.kubernetes.io/name":       fmt.Sprintf("%s-monitoring", params.OtelCol.Name),
we can't use the -monitoring suffix for the pod monitor, as that's the name for the service

2024-01-31 19:33 UTC, jaronoff97 commented on internal/manifests/manifestutils/labels.go
> +func SelectorMatchLabels(instance metav1.ObjectMeta, component string) map[string]string {
bump on the comment :)

2024-01-31 19:50 UTC, jaronoff97 requested changes
i meant to click request changes for that podmonitor issue

2024-02-12 11:41 UTC, yuriolisa commented
> i meant to click request changes for that podmonitor issue

Added the comment and changed the PodMonitor matchLabels to default one.

2024-02-12 18:25 UTC, jaronoff97 reviewed
one comment, otherwise i think this is looking good!

2024-02-12 18:25 UTC, jaronoff97 commented on tests/e2e-prometheuscr/create-pm-prometheus-exporters/01-assert.yaml
> +      app.kubernetes.io/name: simplest-collector-monitoring
this should only be on the servicemonitor right?

2024-02-13 16:02 UTC, jaronoff97 commented
looks like some legit e2e and lint failures

2024-02-13 16:14 UTC, jaronoff97 commented on internal/manifests/manifestutils/labels.go
> +		"app.kubernetes.io/name":       naming.ServiceMonitorSelectorName(instance.Name),
I think we could just reuse [this method](https://github.com/open-telemetry/opentelemetry-operator/blob/00d2a0472fa9ce03f3b777899069a1f56f244846/internal/naming/main.go#L113-L116)

2024-02-13 17:13 UTC, jaronoff97 commented on internal/manifests/manifestutils/labels.go
> +		"app.kubernetes.io/name":       naming.ServiceMonitorSelectorName(instance.Name),
bump on this, no need to define a new method IMO

2024-02-29 15:57 UTC, jaronoff97 approved these changes
one tiny comment, but i don't think it really matters.

2024-02-29 15:57 UTC, jaronoff97 commented on internal/manifests/collector/podmonitor.go
> +	labels := manifestutils.Labels(params.OtelCol.ObjectMeta, name, params.OtelCol.Spec.Image, ComponentOpenTelemetryCollector, []string{})
nit: we can just pass nil at the end here.

2024-02-29 16:08 UTC, swiatekm-sumo reviewed
Can we add a e2e test similar to this one: https://github.com/open-telemetry/opentelemetry-operator/tree/main/tests/e2e-targetallocator/targetallocator-prometheuscr? I'd like to check that our generated PodMonitors and ServiceMonitors allow us to actually scrape collector metrics.

2024-02-29 17:25 UTC, iblancasa approved these changes

2024-03-05 16:31 UTC, jaronoff97 commented on internal/manifests/collector/servicemonitor_test.go
> +		"app.kubernetes.io/name":       naming.MonitoringService(params.OtelCol.Name),
@yuriolisa i realized that we actually need to update the monitoring service for the collector to have its own special label in the same way we do for headless and instead match on that.

2024-03-07 20:22 UTC, jaronoff97 commented on internal/manifests/collector/service.go
> +	headlessExists   = "Exists"
i think we can consolidate here

2024-03-07 20:22 UTC, jaronoff97 commented on internal/manifests/collector/servicemonitor.go
> -	selectorMatchLabels := manifestutils.SelectorMatchLabels(params.OtelCol.ObjectMeta, ComponentOpenTelemetryCollector)
we should still be using this to match on the overall labels we expect the service to have, otherwise our match would be too wide

2024-03-08 08:28 UTC, pavolloffay approved these changes

2024-03-08 14:55 UTC, jaronoff97 reviewed
Just one last thing to improve test confidence, but the overall logic here looks 👌

2024-03-08 14:55 UTC, jaronoff97 commented on tests/e2e-prometheuscr/create-sm-prometheus-exporters/06-assert.yaml
> +      app.kubernetes.io/managed-by: opentelemetry-operator
for these asserts, one thing that would also be helpful is to assert that the monitoring service for this selector has the labels the servicemonitor expects.

2024-03-11 14:55 UTC, jaronoff97 approved these changes

2024-03-11 17:47 UTC, merged