Don't unnecessarily take ownership of PersistentVolumes and PersistentVolumeClaims
open-telemetry/opentelemetry-operator pull request #3097
Opened 2024-07-03 10:28 UTC by swiatekm

**Description:**
Fixed a bug where we'd unnecessarily watch PVs and PVCs without ever creating any. For mysterious reasons, this caused issues when running the operator scoped to a single namespace, using a Role for RBAC. See #3042.

**Link to tracking Issue(s):** #3042

2024-07-03 13:38 UTC, jaronoff97 approved these changes

2024-07-03 17:25 UTC, iblancasa approved these changes

2024-07-03 17:28 UTC, iblancasa requested changes
This was added here https://github.com/open-telemetry/opentelemetry-operator/pull/2575

Because of this: https://github.com/open-telemetry/opentelemetry-operator/issues/2587

Are we sure we can remove this without any implications?

2024-07-03 19:25 UTC, swiatekm commented
@yuriolisa can you have a look as the author of #2575? It doesn't look like we're actually deleting PVCs left after deleting a StatefulSet, nor do I think we should be.

2024-08-26 20:18 UTC, yuriolisa approved these changes
LGTM

2024-08-27 07:39 UTC, merged