Add support for podSecurityContext
open-telemetry/opentelemetry-operator pull request #469
Opened 2021-10-24 16:15 UTC by ekarlso

Fixes: #468

2021-10-30 09:07 UTC, VineethReddy02 requested changes

2021-10-30 09:07 UTC, VineethReddy02 commented on bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml
> +    controller-gen.kubebuilder.io/version: v0.4.6
@ekarlso You need to update your local `kubebuilder` version you are changing the version from `0.6.0` to `0.4.6`I created a test PR on top of your commit you can use it as reference here is the [commit](https://github.com/open-telemetry/opentelemetry-operator/pull/489/commits/a6f64017450091cff982db6092786dfec956464a) and the CI is successful.

2021-11-01 12:18 UTC, pavolloffay commented on bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
> +    generateName: mopentelemetrycollector.kb.io
Now the master uses operator-sdk 1.13.1 put in on your $PATH when generating the bundle.

2021-11-12 20:32 UTC, VineethReddy02 approved these changes
LGTM!

2021-11-17 09:52 UTC, merged